export const REDUCER_CONSTANTS = {
    CART_ADD_ITEM: 'CART_ADD_ITEM',
    CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
    LOGIN: 'AUTH_LOGIN',
    LOGOUT: 'AUTH_LOGOUT',
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_FAILURE: 'GET_PRODUCTS_FAILURE',
    GET_PRODUCTS_BEGIN: 'GET_PRODUCTS_BEGIN',
    GET_COUNTRYLIST_SUCCESS:'GET_COUNTRYLIST_SUCCESS',
    GET_COUNTRYLIST_FAILURE:'GET_COUNTRYLIST_FAILURE'

}